### ISSUE TITLE
Pixels with zero confidence!?

### ISSUE THREAD

**Issue by nischnei** [poolio/bilateral_solver#2]
For depth upsampling I would like to get rid of the prior upsampling step (linear or bilinear upsampling e.g. to get the same resolution as the target image). I tried to tackle this by setting the confidences for those inputs to zero. However, due to the following division:

// Flat initialization
y0 = self.grid.splat(xw) / w_splat

the operation fails. Any recommendations?

**Comment by jonbarron** [comment]
I would guess that you're getting a divide-by-zero issue? If that's the case then you can just clamp w_splat to be at least numerical epsilon: something like np.maximum(w_splat.max, 0.00001). Can you clarify if it's a divide-by-zero error?

**Comment by nischnei** [comment]
Yes, it's a divide-by-zero issue. I was hoping to avoid the "numerical epsilon" as it includes (in my case) default values which are just totally wrong (-1). For zero confidence it would make sense to just incorporate the smoothness term - which would be fine if I regard equation (1) from the paper. I will go through the math and code and hope to provide a fix if anyone has the same issue.

**Comment by jonbarron** [comment]
I wouldn't worry about clamping to epsilon having the effect of letting zero-confidence pixels change the output. I believe the numerator is actually zero too for these cases, so all you're doing is fixing a divide-by-zero error.

**Comment by RoyiAvital** [comment]
Is there a place the Optimized Code is available to replicate the speed in the article?

**Comment by jonbarron** [comment]
No, sorry, that code is too heavily entangled with Google's code repository
for us to easily open-source it.

**Comment by RoyiAvital** [comment]
Could you shed light about how was the performance achieved?
As in the Python code it seems you explicitly define matrix A which in real world problem might no feasible (Too large).

**Comment by jonbarron** [comment]
Explicitly defining the A matrix isn't intractable (as evidenced by the
fact that this python code runs), it's the W matrix in the paper that's too
large and dense to store in memory. In our production code we effectively
construct A as well, we just use PCG to approximately solve it rather than
using a direct sparse matrix solver as we do in the python reference code.

**Comment by RoyiAvital** [comment]
I see.
I thought A would be also dense matrix.

By the way, the [Python Code](https://github.com/poolio/bilateral_solver/blob/master/notebooks/bilateral_solver.ipynb) does use *PCG* to solve the problem. Though it seems it uses the simpler conditioning if I got it right.

**Comment by jonbarron** [comment]
Oh, you're right! My mistake. We just didn't implement the hierarchical
preconditioning in this version.
