### ISSUE TITLE
Pictures in the paper

### ISSUE THREAD

**Issue by jiujiao** [poolio/bilateral_solver#7]
hi！I'm reading your paper recently，I'm very interested in it.I want to try to do some experiments，So I need some pictures in this paper.If it is convenient for you, can you send me the pictures used in your paper, especially those processed by mc-cnn.
Thank you a thousand times！

**Comment by jonbarron** [comment]
All we have publicly available are outputs for the depth superresolution experiments (available [here](https://drive.google.com/file/d/0B4nuwEMaEsnmaDI3bm5VeDRxams/view)). The MC-CNN results were produced by applying MC-CNN to the middlebury stereo dataset.

**Comment by jiujiao** [comment]
> All we have publicly available are outputs for the depth superresolution experiments (available [here](https://drive.google.com/file/d/0B4nuwEMaEsnmaDI3bm5VeDRxams/view)). The MC-CNN results were produced by applying MC-CNN to the middlebury stereo dataset.

OK，thank you very much！
